name: backend-tests

on:
  # Fires for any activity that changes the pull-request’s HEAD commit
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main] # protect additional target branches as needed
    paths: # (optional) only run when backend code changes
      - "server/**"
  # Required if you use GitHub’s “merge queue” feature
  merge_group: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: npm ci
        working-directory: ./server

      - name: Run Jest Tests
        run: npm run test:e2e
        working-directory: ./server
