name: Build, Terraform, and Deploy React App

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CI: ""

jobs:
  terraform-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get Terraform Outputs
        id: tf_outputs
        run: |
          echo "INSTANCE_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV

      # Build the React App
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Zip Build Output
        run: zip -r react-build.zip build

      # Upload to EC2
      - name: Upload React Build to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "react-build.zip"
          target: "~/"

      # Deploy on EC2
      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install dependencies
            sudo yum install -y unzip nginx

            # Create a new app directory
            mkdir -p ~/my-react-app

            # Unzip build into that directory
            unzip -o ~/react-build.zip -d ~/my-react-app

            # Write Nginx config
            cat <<EOF | sudo tee /etc/nginx/conf.d/react.conf
            server {
              listen 80;
              server_name _;

              root /home/ec2-user/my-react-app;
              index index.html;

              location / {
                try_files \$uri /index.html;
              }
            }
            EOF

            # Remove the default site config (optional but cleaner)
            sudo rm -f /etc/nginx/conf.d/default.conf

            # Restart Nginx
            sudo systemctl restart nginx
